# Generated by Django 3.1.2 on 2020-10-19 09:04

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, verbose_name='detection model name')),
                ('configuration_file_path', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='files/models'), upload_to='')),
                ('weight_file_path', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='files/models'), upload_to='')),
                ('class_file_path', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='files/models'), upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
