# Generated by Django 3.1.2 on 2020-10-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionmodel',
            name='name',
            field=models.CharField(max_length=300, verbose_name='detection model name'),
        ),
    ]
