# Generated by Django 3.1.2 on 2020-10-19 09:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multimedia_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, verbose_name='capture name')),
                ('path', models.TextField(help_text='This value can be one number (device index, is just the number to specify which camera), or url camera, or name of a video/image file (file path).', verbose_name='file path or camera url')),
                ('latitude', models.CharField(blank=True, help_text='Latitude where the videos or images were taken, or where the cameras are located.', max_length=30, null=True, verbose_name='capture latitude')),
                ('longitude', models.CharField(blank=True, help_text='Longitude where the videos or images were taken, or where the cameras are located.', max_length=30, null=True, verbose_name='capture longitude')),
                ('capture_date', models.DateTimeField(blank=True, null=True, verbose_name='capture date')),
                ('other', models.JSONField(blank=True, null=True, verbose_name='other data')),
                ('multimedia_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia_types.multimediatype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
