# Generated by Django 3.1.2 on 2020-10-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='capture_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='capture date'),
        ),
    ]
