# Generated by Django 3.1.2 on 2020-11-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0002_auto_20201021_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='image_path',
            field=models.TextField(help_text='Image path from calibration', null=True, verbose_name='camera calibration image path'),
        ),
        migrations.AddField(
            model_name='capture',
            name='points',
            field=models.JSONField(blank=True, null=True, verbose_name='points data'),
        ),
    ]
