# Generated by Django 3.1.2 on 2020-11-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0003_auto_20201102_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capture',
            name='image_path',
        ),
        migrations.AddField(
            model_name='capture',
            name='calibr_image_name',
            field=models.CharField(help_text='Camera calibration image name', max_length=255, null=True, verbose_name='camera calibration image name'),
        ),
        migrations.AddField(
            model_name='capture',
            name='calibr_image_path',
            field=models.ImageField(help_text='Camera calibration image path', null=True, upload_to='', verbose_name='camera calibration image path'),
        ),
        migrations.AddField(
            model_name='capture',
            name='image_size',
            field=models.JSONField(null=True, verbose_name='calibration image size or video frames'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='other',
            field=models.JSONField(null=True, verbose_name='other data'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='points',
            field=models.JSONField(null=True, verbose_name='points data'),
        ),
    ]
