# Generated by Django 3.1.2 on 2020-11-07 19:09

from django.db import migrations, models
import hefesto_be.fire.captures.models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0004_auto_20201102_0345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capture',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='capture',
            name='calibr_image_name',
            field=models.CharField(default='1604776161.PNG', help_text='Camera calibration image name', max_length=255, null=True, verbose_name='camera calibration image name'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='calibr_image_path',
            field=models.ImageField(blank=True, help_text='Camera calibration image path', null=True, upload_to=hefesto_be.fire.captures.models.capture_image_path, verbose_name='camera calibration image path'),
        ),
    ]
