# Generated by Django 3.1.2 on 2021-01-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0006_auto_20201107_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='dist_calibr_metric',
            field=models.JSONField(null=True, verbose_name='distance calibration metric'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='calibr_image_name',
            field=models.CharField(default='1611691948.PNG', help_text='Camera calibration image name', max_length=255, null=True, verbose_name='camera calibration image name'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='image_size',
            field=models.JSONField(null=True, verbose_name='calibration image size or video frames, { width: value, height: value}'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='points',
            field=models.JSONField(null=True, verbose_name='points data, { point: { center: { x: value, y: value}, vertical: { x: value, y: value}, horizontal: { x: value, y: value}},rectangle: [{ x: value, y: value},{ x: value, y: value}, { x: value, y: value},{ x: value, y: value}]}'),
        ),
    ]
