# Generated by Django 3.1.2 on 2021-01-26 21:11

from django.db import migrations, models
import hefesto_be.fire.captures.models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0007_auto_20210126_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='calibr_image_name',
            field=models.CharField(default='1611695513.PNG', help_text='Camera calibration image name', max_length=255, null=True, verbose_name='camera calibration image name'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='dist_calibr_metric',
            field=models.JSONField(default=hefesto_be.fire.captures.models.distance_calibration_metric, null=True, verbose_name='distance calibration metric in cm (radius)'),
        ),
    ]
