# Generated by Django 3.1.2 on 2021-01-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('captures', '0008_auto_20210126_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='filter_labels',
            field=models.ManyToManyField(blank=True, related_name='captures', to='labels.Label'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='calibr_image_name',
            field=models.CharField(default='1611803963.PNG', help_text='Camera calibration image name', max_length=255, null=True, verbose_name='camera calibration image name'),
        ),
    ]
