# Generated by Django 3.1.2 on 2021-01-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('captures', '0009_auto_20210128_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='calibr_image_name',
            field=models.CharField(default='1611806054.PNG', help_text='Camera calibration image name', max_length=255, null=True, verbose_name='camera calibration image name'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='filter_labels',
            field=models.ManyToManyField(blank=True, to='labels.Label'),
        ),
    ]
