# Generated by Django 3.1.2 on 2021-01-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_remove_label_detection_model'),
        ('captures', '0011_auto_20210128_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='calibr_image_name',
            field=models.CharField(default='1611810049.PNG', help_text='Camera calibration image name', max_length=255, null=True, verbose_name='camera calibration image name'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='filter_labels',
            field=models.ManyToManyField(to='labels.Label'),
        ),
    ]
