# Generated by Django 3.1.2 on 2021-01-28 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='detection_model',
        ),
    ]
