# Generated by Django 3.1.2 on 2021-01-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_remove_label_detection_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='label name'),
        ),
    ]
