# Generated by Django 3.1.2 on 2020-10-19 09:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('file_name', models.CharField(max_length=100, verbose_name='detection file name')),
                ('file_path', models.FileField(upload_to='', verbose_name='detection file path')),
                ('processing_date', models.DateTimeField(verbose_name='processing date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetectionLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('safe_count', models.PositiveSmallIntegerField(null=True)),
                ('low_risk_count', models.PositiveSmallIntegerField(null=True)),
                ('high_risk_count', models.PositiveSmallIntegerField(null=True)),
                ('other_metrics', models.JSONField(null=True)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detections.detection')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labels.label')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='detection',
            name='detection_by_label',
            field=models.ManyToManyField(through='detections.DetectionLabel', to='labels.Label'),
        ),
    ]
