# Generated by Django 3.1.2 on 2020-10-21 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection_models', '0002_auto_20201021_0223'),
        ('captures', '0002_auto_20201021_0223'),
        ('detections', '0002_auto_20201021_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='capture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='captures.capture'),
        ),
        migrations.AddField(
            model_name='detection',
            name='detection_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='detection_models.detectionmodel'),
        ),
    ]
