# Generated by Django 3.1.2 on 2021-01-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0003_auto_20201021_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='detection_by_label',
        ),
        migrations.AddField(
            model_name='detection',
            name='detection_metrics',
            field=models.JSONField(null=True, verbose_name='detection metrics'),
        ),
        migrations.AddField(
            model_name='detection',
            name='high_risk_count',
            field=models.IntegerField(null=True, verbose_name='safe count'),
        ),
        migrations.AddField(
            model_name='detection',
            name='low_risk_count',
            field=models.IntegerField(null=True, verbose_name='safe count'),
        ),
        migrations.AddField(
            model_name='detection',
            name='other_metrics',
            field=models.JSONField(null=True, verbose_name='other metrics'),
        ),
        migrations.AddField(
            model_name='detection',
            name='safe_count',
            field=models.IntegerField(null=True, verbose_name='safe count'),
        ),
    ]
